# Generated by Django 4.0.6 on 2022-08-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_maritalstatus_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
    ]
